name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI - OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [24.x]
        elixir: [1.12.x, 1.13.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          deps
          /usr/local/bin
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - name: Install Dependencies
      shell: bash
      run: |
        mix local.rebar --force && mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
